### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by jiezhang165** [layumi/AICIty-reID-2020#36]
请问训练和测试用的数据集是AICity20 官网的Track2吗？我在官网下载了压缩包，但解压后不是以下格式：
    |- 2020AICITY
        |- ...
        |- 000345_c020_9.jpg
        |- ...
        |- 002028_c036_4_9_95_2.jpg
请问需要重新组织官网数据集吗？

**Comment by lzd0825** [comment]
官网上数据集的下载链接是不是有问题?
比如“Track 4: Traffic Anomaly Detection”的数据集，下载到35%左右的时候就中断了，是什么原因啊？
您能否给我发一个新的下载链接？

**Comment by xh7682** [comment]
请问数据集如何下载呢？AI CITY CHALLENGE官网有密码保护，具体应该如何下载呢？

**Comment by xh7682** [comment]
> 请问训练和测试用的数据集是AICity20 官网的Track2吗？我在官网下载了压缩包，但解压后不是以下格式：
> |- 2020AICITY
> |- ...
> |- 000345_c020_9.jpg
> |- ...
> |- 002028_c036_4_9_95_2.jpg
> 请问需要重新组织官网数据集吗？

请问数据集如何下载呢？AI CITY CHALLENGE官网有密码保护，具体应该如何下载呢？

**Comment by xh7682** [comment]
> @jiezhang165
> Follow the guidance of this link: https://github.com/PaddlePaddle/Research/tree/master/CV/PaddleReid/process_aicity_data
> You have to prepare your dataset before training. You may also need to make some other changes.
> 
> 遵循此链接的指导：https://github.com/PaddlePaddle/Research/tree/master/CV/PaddleReid/process_aicity_data
> 您必须准备要训练的数据集。 您可能还需要做一些其他更改。
> 
> > 请问训练和测试用的数据集是AICity20 官网的Track2吗？我在官网下载了压缩包，但解压后不是以下格式：
> > |- 2020AICITY
> > |- ...
> > |- 000345_c020_9.jpg
> > |- ...
> > |- 002028_c036_4_9_95_2.jpg
> > 请问需要重新组织官网数据集吗？

请问数据集如何下载呢？AI CITY CHALLENGE官网有密码保护，具体应该如何下载呢？

**Comment by layumi** [comment]
Hi @xh7682 
You need to agree several licenses and send the email to the AICity organizer.

**Comment by xh7682** [comment]
> Hi @xh7682
> You need to agree several licenses and send the email to the AICity organizer.

好的，谢谢！

**Comment by lhbsww** [comment]
(one_env) luhu@omnisky:~/data/2020AICITY/data/AIC20_ReID$ python _prepare_syn_trainlist.py
Traceback (most recent call last):
  File "_prepare_syn_trainlist.py", line 29, in <module>
    color = s.attributes['colorID'].value
  File "/home/luhu/anaconda3/envs/one_env/lib/python3.6/xml/dom/minidom.py", line 552, in __getitem__
    return self._attrs[attname_or_tuple]
KeyError: 'colorID'
请问在对数据进行处理的时候出现这个错误，是因为什么，要怎么解决呢

**Comment by layumi** [comment]
Hi @lhbsww

Please refer to https://github.com/layumi/AICIty-reID-2020/issues/7
