### ISSUE TITLE
python train_2020.py

### ISSUE THREAD

**Issue by s20163081161** [layumi/AICIty-reID-2020#9]
@layumi 郑博士 我直接运行python train_2020.py能真确开始训练，但是按照README.md上提供的那一长传命令，就会报下面的错，这是为何？

requests.exceptions.SSLError: HTTPSConnectionPool(host='data.lip6.fr', port=443): Max retries exceeded with url: /cadene/pretrainedmodels/se_resnext101_32x4d-3b2fe3d8.pth (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by layumi** [comment]
应该是有墙。。下SENet 预训练模型的时候报错了

**Comment by daiguangzhao** [comment]
> @layumi 郑博士 我直接运行python train_2020.py能真确开始训练，但是按照README.md上提供的那一长传命令，就会报下面的错，这是为何？
> 
> requests.exceptions.SSLError: HTTPSConnectionPool(host='data.lip6.fr', port=443): Max retries exceeded with url: /cadene/pretrainedmodels/se_resnext101_32x4d-3b2fe3d8.pth (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

加上以下代码，原因你自己ＣＳＤＮ哈：
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

**Comment by daiguangzhao** [comment]
郑博士，你好，请问
name SE_imbalance_s1_384_p0.5_lr2_mt_d0_b24+v+aug，这个对应哪一块代码，论文哪里提到了？麻烦，谢谢

**Comment by s20163081161** [comment]
> > @layumi 郑博士 我直接运行python train_2020.py能真确开始训练，但是按照README.md上提供的那一长传命令，就会报下面的错，这是为何？
> > requests.exceptions.SSLError: HTTPSConnectionPool(host='data.lip6.fr', port=443): Max retries exceeded with url: /cadene/pretrainedmodels/se_resnext101_32x4d-3b2fe3d8.pth (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
> 
> 加上以下代码，原因你自己ＣＳＤＮ哈：
> import ssl
> 
> ssl._create_default_https_context = ssl._create_unverified_context

我直接翻墙下载了

**Comment by HanwenCao** [comment]
> 郑博士，你好，请问
> name SE_imbalance_s1_384_p0.5_lr2_mt_d0_b24+v+aug，这个对应哪一块代码，论文哪里提到了？麻烦，谢谢

请问您知道了吗？

**Comment by layumi** [comment]
@HanwenCao 
这就是 SENet的basic model，跑的时候起的名字。

**Comment by lhbsww** [comment]
Traceback (most recent call last):
  File "train_2020.py", line 441, in <module>
    model = ft_net_SE(len(class_names), opt.droprate, opt.stride, opt.pool)
  File "/home/luhu/AIC/model.py", line 317, in __init__
    model_ft = pretrainedmodels.__dict__[model_name](num_classes=1000, pretrained='imagenet')
  File "/home/luhu/anaconda3/envs/one_env/lib/python3.6/site-packages/pretrainedmodels/models/senet.py", line 441, in se_resnext101_32x4d
    initialize_pretrained_model(model, num_classes, settings)
  File "/home/luhu/anaconda3/envs/one_env/lib/python3.6/site-packages/pretrainedmodels/models/senet.py", line 373, in initialize_pretrained_model
    model.load_state_dict(model_zoo.load_url(settings['url']))
  File "/home/luhu/anaconda3/envs/one_env/lib/python3.6/site-packages/torch/hub.py", line 528, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/luhu/anaconda3/envs/one_env/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/luhu/anaconda3/envs/one_env/lib/python3.6/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.


请问在执行train_2020.py时，出现这个错误是什么原因，要怎么解决
